"""migrates3

Revision ID: 5ad5388f79f4
Revises: d78609617162
Create Date: 2026-01-10 23:51:05.362366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad5388f79f4'
down_revision: Union[str, Sequence[str], None] = 'd78609617162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('votes_amount', sa.Integer(), nullable=True))
    op.add_column('list', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'created_at')
    op.drop_column('film', 'votes_amount')
    # ### end Alembic commands ###
