"""dates of user login and register

Revision ID: 9661f8c05ce6
Revises: cec0bdbe6962
Create Date: 2026-01-10 21:35:05.449893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9661f8c05ce6'
down_revision: Union[str, Sequence[str], None] = 'cec0bdbe6962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
