"""migrates2

Revision ID: d78609617162
Revises: 9661f8c05ce6
Create Date: 2026-01-10 23:48:14.252635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78609617162'
down_revision: Union[str, Sequence[str], None] = '9661f8c05ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country', ['country_name'])
    op.add_column('user', sa.Column('logged_out_at', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('logged_out_at2', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'logged_out_at2')
    op.drop_column('user', 'logged_out_at')
    op.drop_constraint(None, 'country', type_='unique')
    # ### end Alembic commands ###
